<a href="https://colab.research.google.com/github/lukaszplust/data-science-learn/blob/main/011_020_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 11](#1)
* [Ćwiczenie 12](#2)
* [Ćwiczenie 13](#3)
* [Ćwiczenie 14](#4)
* [Ćwiczenie 15](#5)
* [Ćwiczenie 16](#6)
* [Ćwiczenie 17](#7)
* [Ćwiczenie 18](#8)
* [Ćwiczenie 19](#9)
* [Ćwiczenie 20](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 11
Zbuduj jednowymiarową tablicę numpy liczb dwucyfrowych.

__Oczekiwany wynik:__


```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```



__Wskazówka:__ Użyj funkcji _np.arange()_.


In [2]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Ćwiczenie 12
Zbuduj tablicę numpy określoną poniżej:


```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Zwróć uwagę, że kształt tablicy to (9, 10).


__Wskazówka:__ Użyj funkcji _np.arange()_ oraz metodę _np.ndarray.reshape()_.

In [8]:
new = np.arange(10,100)
new1 = new.reshape(9,10)
new1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Przypomnienie

###  Macierz jednostkowa:

Macierz jednostkowa - macierz kwadratowa, której współczynniki podane są wzorem:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Przykłady
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Ćwiczenie 13
Zbuduj tablicę dwuwymiarową (macierz jednostkową) o kształcie _6x6_ mającą na przekątnej jedynki oraz poza same zera. Użyj typu danych _int_.
__Oczekiwany wynik:__


```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```



__Wskazówka:__ Użyj funkcji _np.eye()_.

In [9]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Ćwiczenie 14
Ustaw ziarno losowe na wartość 10. Następnie zbuduj jednowymiarową tablicę składającą się z 30 pseudolosowo wygenerowanych wartości z rozkładu jednostajnego nad przedziałem $[0, 1)$.

__Oczekiwany wynik:__


```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```



__Wskazówka:__ Użyj funkcji _np.random.rand()_.

In [10]:
np.random.seed(10)
np.random.rand(30)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])

### <a name='5'></a> Ćwiczenie 15
Ustaw ziarno losowe na wartość 20. Następnie zbuduj dwuwymiarową tablicę o kształcie _(10, 4)_ wartości pseudolosowo wygenerowanych ze standardowego rozkładu normalego $N(0, 1)$.

__Oczekiwany wynik:__


```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```



__Wskazówka:__ Użyj funkcji _np.random.randn()_.

In [12]:
np.random.seed(20)
np.random.randn(10,4)

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])

### <a name='6'></a> Ćwiczenie 16
Ustaw ziarno losowe na wartość 30. Następnie zbuduj dwuwymiarową tablicę o kształcie _(10, 4)_ wartości pseudolosowo wygenerowanych z rozkładu normalego $N(100, 5)$.  
$\mu=100$   
$\sigma^{2}=5$

__Oczekiwany wynik:__


```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```



__Wskazówka:__ Użyj funkcji _np.random.randn()_.

In [14]:
np.random.seed(30)

sigma = np.sqrt(5)

mu = 100

sigma * np.random.randn(10,4) + mu


array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])

### <a name='7'></a> Ćwiczenie 17
Iterując po tablicy numpy $A$ element po elemencie (element-wise) wydrukuj każdy element tablicy do konsoli.


```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```



__Wskazówka:__ Użyj funkcji _np.nditer()_.

In [15]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

for i in np.nditer(A):
  print(i)

1
4
3
5
2
6


### <a name='8'></a> Ćwiczenie 18
Utwórz jednowymiarową tablicę numpy (wektor) składający się z 11 równo rozmieszczonych punktów z przedziału $[0, 1].$

__Oczekiwany wynik:__


```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Wskazówka:__ Użyj funkcji _np.linspace()_.


In [17]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### <a name='9'></a> Ćwiczenie 19
Ustaw ziarno losowe na wartość 42. Wygeneruj tablicę jednowymiarową (wektor) zawierający możliwy wynik losowania w grę Duży Lotek. 

__Oczekiwany wynik:__


```
array([39, 29, 15, 43,  8, 21])
```



__Wskazówka:__ Wynikiem losowania jest 6-elementowy wektor wartości od 1 do 49 włącznie.

In [18]:
np.random.seed(42)
np.random.randint(1,49,6)

array([39, 29, 15, 43,  8, 21])

### <a name='10'></a> Ćwiczenie 20
Zbuduj dwuwymiarową tablicę numpy rozmiaru _6x6_ podaną poniżej:


```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Wskazówka:__ Użyj funkcji _np.diag()_.


In [21]:
np.diag(np.arange(6))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])