<a href="https://colab.research.google.com/github/lukaszplust/data-science-learn/blob/main/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [5]:
import numpy as np

np.random.seed(42)
np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [9]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])

B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate([A,B],axis=0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [10]:
np.concatenate([A,B],axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [11]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate([data,target],axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [12]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack([feature1,feature2,feature3])

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [44]:
#ehh znowu ogarnąć to wycinanie :))!!!!!
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
print(A)
print('--')
A1,A2,A3 = np.split(A,[2,6],axis=1) # kolumna 0 i 1 to pierwsza, kolumna 2,3,4,5 to druga, kolumna 5 i 6 to trzecia
print(A1)
print(A2)
print(A3)


[[0 0 4 5 5 6 1 1]
 [0 0 5 5 6 6 1 1]
 [0 0 6 4 3 6 1 1]
 [0 0 2 3 6 5 1 1]
 [0 0 2 5 0 1 1 1]]
--
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 5 5 6]
 [5 5 6 6]
 [6 4 3 6]
 [2 3 6 5]
 [2 5 0 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [55]:
A = np.random.randint(low=0, high=2, size=(10, 6))
print(np.count_nonzero(A))
A

29


array([[1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0]])

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [56]:
np.count_nonzero(A,axis=1)

array([1, 4, 2, 4, 2, 2, 2, 4, 4, 4])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [71]:
A = np.random.randn(10, 4)
A

array([[-0.639 , -1.3231,  1.642 ,  1.0098],
       [-0.6882,  2.2524,  0.9818, -0.3248],
       [-2.4994,  2.2909, -1.3896, -1.6454],
       [ 1.0226,  2.4398,  1.3843,  0.5639],
       [ 0.5948,  0.8534,  0.7589,  0.2812],
       [ 0.1042, -0.0626, -0.754 , -0.2807],
       [-1.693 , -0.0983, -0.9886, -1.1036],
       [ 0.1799,  1.392 ,  0.9183, -1.5705],
       [-0.9896,  0.9408, -0.9825, -0.2246],
       [ 0.5501, -0.9683,  0.1054, -1.334 ]])

In [74]:
np.set_printoptions(precision=2)
print(f' z precyzją do 2 miejsc: {A}')

 z precyzją do 2 miejsc: [[-0.64 -1.32  1.64  1.01]
 [-0.69  2.25  0.98 -0.32]
 [-2.5   2.29 -1.39 -1.65]
 [ 1.02  2.44  1.38  0.56]
 [ 0.59  0.85  0.76  0.28]
 [ 0.1  -0.06 -0.75 -0.28]
 [-1.69 -0.1  -0.99 -1.1 ]
 [ 0.18  1.39  0.92 -1.57]
 [-0.99  0.94 -0.98 -0.22]
 [ 0.55 -0.97  0.11 -1.33]]


### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [75]:
A = np.array([1.2e-6, 1.7e-7])
A

array([1.2e-06, 1.7e-07])

In [77]:
np.set_printoptions(precision=8, suppress=True)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [79]:
A = np.random.randn(8, 4)
A


array([[-0.18528766, -0.1298207 ,  0.04381147, -0.147002  ],
       [ 0.96387912,  2.210523  , -0.55749179, -1.36980298],
       [-0.08828205,  2.57970934, -0.80367457,  1.63911681],
       [ 1.67770081, -0.55358824,  0.56898308,  1.62839662],
       [-0.37912774, -0.20358036, -0.58168091, -1.01475673],
       [-0.64927755, -1.22394027,  0.03408347, -0.76997323],
       [ 0.23378591, -1.55589565,  0.33088023,  0.83352896],
       [-1.99373564,  0.37405657,  1.22766899, -1.20964102]])

In [81]:
np.delete(A,2,axis=1)

array([[-0.18528766, -0.1298207 , -0.147002  ],
       [ 0.96387912,  2.210523  , -1.36980298],
       [-0.08828205,  2.57970934,  1.63911681],
       [ 1.67770081, -0.55358824,  1.62839662],
       [-0.37912774, -0.20358036, -1.01475673],
       [-0.64927755, -1.22394027, -0.76997323],
       [ 0.23378591, -1.55589565,  0.83352896],
       [-1.99373564,  0.37405657, -1.20964102]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [86]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [89]:
A = np.random.randint(10, size=(100, 30))
A


array([[6, 4, 5, ..., 7, 0, 6],
       [4, 3, 6, ..., 5, 3, 5],
       [8, 9, 9, ..., 3, 6, 1],
       ...,
       [0, 3, 8, ..., 2, 3, 5],
       [6, 3, 3, ..., 0, 3, 9],
       [4, 8, 6, ..., 0, 9, 7]])

In [92]:
np.set_printoptions(edgeitems=10) # domyslnie jest ich tu 3 jak widac u góry
A

array([[6, 4, 5, 9, 3, 1, 9, 8, 9, 6, ..., 9, 1, 1, 7, 0, 6, 4, 7, 0, 6],
       [4, 3, 6, 9, 1, 0, 0, 0, 4, 9, ..., 2, 9, 0, 5, 1, 0, 1, 5, 3, 5],
       [8, 9, 9, 7, 0, 7, 8, 5, 9, 4, ..., 7, 8, 9, 8, 9, 8, 1, 3, 6, 1],
       [0, 2, 3, 7, 5, 1, 8, 1, 4, 3, ..., 7, 5, 3, 3, 5, 3, 7, 8, 0, 3],
       [3, 1, 5, 2, 6, 4, 3, 4, 7, 2, ..., 3, 6, 7, 0, 4, 2, 0, 2, 5, 6],
       [7, 3, 2, 4, 8, 5, 8, 5, 1, 4, ..., 9, 2, 3, 2, 0, 9, 4, 0, 0, 1],
       [3, 5, 7, 2, 0, 2, 2, 4, 3, 3, ..., 4, 5, 2, 7, 3, 7, 9, 9, 2, 9],
       [6, 8, 3, 7, 2, 6, 2, 6, 9, 9, ..., 7, 7, 3, 5, 7, 6, 6, 3, 8, 9],
       [5, 2, 4, 4, 4, 7, 8, 8, 5, 5, ..., 6, 1, 8, 9, 8, 5, 2, 0, 3, 2],
       [0, 2, 3, 7, 8, 2, 5, 9, 4, 5, ..., 0, 8, 9, 9, 8, 6, 1, 5, 3, 0],
       ...,
       [7, 6, 8, 4, 9, 2, 5, 4, 3, 1, ..., 9, 1, 0, 7, 2, 0, 0, 1, 5, 5],
       [2, 3, 1, 1, 6, 0, 6, 0, 5, 2, ..., 5, 5, 7, 0, 1, 8, 7, 6, 6, 4],
       [1, 5, 9, 2, 3, 9, 1, 1, 7, 7, ..., 7, 6, 9, 8, 4, 1, 6, 7, 6, 6],
       [4, 1, 5, 3, 9, 1, 