<a href="https://colab.research.google.com/github/lukaszplust/data-science-learn/blob/main/191_200_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 191](#1)
* [Ćwiczenie 192](#2)
* [Ćwiczenie 193](#3)
* [Ćwiczenie 194](#4)
* [Ćwiczenie 195](#5)
* [Ćwiczenie 196](#6)
* [Ćwiczenie 197](#7)
* [Ćwiczenie 198](#8)
* [Ćwiczenie 199](#9)
* [Ćwiczenie 200](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
import pandas as pd

np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 191
Z poniższego słownika _data_ utwórz obiekt _DataFrame_ i przypisz do zmiennej _df_.


```
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}
```



In [11]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df = pd.DataFrame(data)
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

Wyświetl podstawowe informacje na temat obiektu _df_.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


Dokonaj konwersji zmiennych na poszczególne typy:
* size -> _category_
* color -> _category_
* gender -> _category_
* weight -> _float_
* bought -> _category_

In [17]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


### <a name='2'></a> Ćwiczenie 192
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _LabelEncoder_ dokonaj kodowania 0-1 zmiennej _bought_. Zmiany przypisz na stałe do obiektu _df_ i wyświetl ten obiekt.

In [27]:
from sklearn.preprocessing import LabelEncoder

#instancja klasy

le = LabelEncoder()
#dopasowanie zmiennej do klasy
df['bought'] = le.fit_transform(df['bought'])

In [21]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

Wykorzystując odpowiednią metodę klasy _LabelEncoder_ przywróć pierwotną postać zmiennej _bought_. Zwróć uwagę na typ zmiennej _bought_.

In [28]:
#PRZYWARACANIE PIEROWENEJ WESJI !!!!!!!!!

df['bought']=le.inverse_transform(df['bought'])

In [29]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

### <a name='3'></a> Ćwiczenie 193
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _OneHotEncoder_ dokonaj kodowania 0-1 zmiennej _size_. Nie przypisuj zmian do obiektu _df_.

Użyj parametru _sparse=False_ klasy _OneHotEncoder_.

In [30]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)

encoder.fit_transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _OneHotEncoder_ dokonaj kodowania 0-1 zmiennej _size_. Nie przypisuj zmian do obiektu _df_.

Użyj parametru _sparse=False_ **oraz _drop=first_** klasy _OneHotEncoder_.

In [31]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False, drop='first')

encoder.fit_transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

### <a name='4'></a> Ćwiczenie 194
Wykorzystując bibliotekę _pandas_ oraz funkcję _get_dummies()_ przedstaw wszystkie zmienne kategoryczne obiektu _df_ w postaci kodowania 0-1. Nie przypisuj zmian na trwałe do obiektu _df_.

In [32]:
pd.get_dummies(df)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0       0       0        1           0            0          1   
1   89.0   450.0       1       0        0           0            1          0   
2   99.0   300.0       0       1        0           1            0          0   
3  129.0   380.0       1       0        0           0            1          0   
4   79.0   410.0       0       1        0           0            0          1   

   gender_female  gender_male  bought_no  bought_yes  
0              1            0          0           1  
1              0            1          1           0  
2              0            1          0           1  
3              1            0          1           0  
4              1            0          0           1

Wykorzystując bibliotekę _pandas_ oraz funkcję _get_dummies()_ przedstaw wszystkie zmienne kategoryczne obiektu _df_ w postaci kodowania 0-1. Użyj parametru _drop_first=True_. Nie przypisuj zmian na trwałe do obiektu _df_.

In [33]:
pd.get_dummies(df, drop_first=True)

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0       0        1            0          1            0   
1   89.0   450.0       0        0            1          0            1   
2   99.0   300.0       1        0            0          0            1   
3  129.0   380.0       0        0            1          0            0   
4   79.0   410.0       1        0            0          1            0   

   bought_yes  
0           1  
1           0  
2           1  
3           0  
4           1

Wykorzystując bibliotekę _pandas_ oraz funkcję _get_dummies()_ przedstaw **zmienną _size_** obiektu _df_ w postaci kodowania 0-1. Użyj parametru _drop_first=True_. Nie przypisuj zmian na trwałe do obiektu _df_.

In [35]:
# zamieniam na 0 i 1 tylko size

In [34]:
pd.get_dummies(df, columns=['size'],drop_first=True)

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes       0        1
1  green    male   89.0   450.0     no       0        0
2   blue    male   99.0   300.0    yes       1        0
3  green  female  129.0   380.0     no       0        0
4    red  female   79.0   410.0    yes       1        0

### <a name='5'></a> Ćwiczenie 195
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _StandardScaler_ dokonaj skalowania zmiennej _weight_. Nie przypisuj zmian do obiektu _df_.

In [38]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

STANDARYZAJCA BARDZO WAŻNE !!!!!

In [37]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

scale.fit_transform(df[['weight']])

array([[ 1.3660019 ],
       [ 0.62360956],
       [-1.60356745],
       [-0.41573971],
       [ 0.02969569]])

### <a name='6'></a> Ćwiczenie 196
Wczytaj raz jeszcze słownik _data_ do obiektu _DataFrame_ o nazwie _df_.

In [39]:
df= pd.DataFrame(data)
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

Przygotuj dane do modelu uczenia maszynowego:
* wykorzystując klasę LabelEncoder dokonaj kodowania 0-1 zmiennej _bought_
* dokonaj standaryzacji zmiennych _weight_ oraz _price_
* dokonaj kodowania 0-1 posoztałych zmiennych kategorycznych wykorzystując funkcję _get_dummies()._

Przypisz zmiany do zmiennej _df_prep_.

In [42]:
#import bibliotek
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

#kopia
df_prep = df.copy()
#instancje klas
scaler = StandardScaler()
encoder = LabelEncoder()

#kodowanie 0 i 1 zmiennej bought
df_prep['bought'] = encoder.fit_transform(df_prep[['bought']])

#standaryzacja zmiennych weight i price
df_prep[['weight', 'price']] = scaler.fit_transform(df_prep[['weight', 'price']])

#kodowanie pozostałych zmiennych kategorycznych
df_prep = pd.get_dummies(df_prep,drop_first=True)
df_prep

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0

### <a name='7'></a> Ćwiczenie 197
Skopiuj obiekt _df_prep_ do zmiennej _data_. Następnie wyrwij z tego obiektu kolumnę _bought_ i przypisz do zmiennej _target_.


In [55]:
data = df_prep.copy()
data

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0

In [56]:
target = data.pop('bought')

In [57]:
target

0    1
1    0
2    1
3    0
4    1
Name: bought, dtype: int64

Wyświetl 5 pierwszych wierszy obiektu _data_. Upewnij się, że nie ma w nim kolumny _bought_.

In [58]:
data.head()

price    weight  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002       0        1            0          1            0
1 -0.691898  0.623610       0        0            1          0            1
2 -0.461266 -1.603567       1        0            0          0            1
3  0.230633 -0.415740       0        0            1          0            0
4 -0.922531  0.029696       1        0            0          1            0

Wyświetl 5 pierwszych wierszy obiektu _target_.

In [59]:
target.head()

0    1
1    0
2    1
3    0
4    1
Name: bought, dtype: int64

### <a name='8'></a> Ćwiczenie 198
Wykorzystując bibliotekę _scikit-learn_ oraz funkcję _train_test_split_ podziel dane z obiektów _data_ i _target_ na zbiór treningowy (_X\_train_, _y\_train_) oraz zbiór testowy (_X\_test_, _y\_test_). Do zbioru testowego przydziel 20% próbek. 

Wyświetl rozmiar obiektów:
* _X\_train_
* _X\_test_
* _y\_train_
* _y\_test_

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'Y_train shape: {y_train.shape}')
print(f'Y_test shape: {y_test.shape}')

X_train shape: (4, 7)
X_test shape: (1, 7)
Y_train shape: (4,)
Y_test shape: (1,)


### <a name='9'></a> Ćwiczenie 199
Połącz obiekty _X\_train_ oraz _X\_test_ w jeden obiekt _DataFrame_ o nazwie _X_.

In [62]:
X_test

price    weight  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002       0        1            0          1            0

In [61]:
X_train

price    weight  size_M  size_XL  color_green  color_red  gender_male
2 -0.461266 -1.603567       1        0            0          0            1
4 -0.922531  0.029696       1        0            0          1            0
3  0.230633 -0.415740       0        0            1          0            0
1 -0.691898  0.623610       0        0            1          0            1

In [65]:
X = pd.concat([X_train, X_test])

### <a name='10'></a> Ćwiczenie 200
Połącz obiekty _y\_train_ oraz _y\_test_ w jeden obiekt _DataFrame_ o nazwie _y_.

In [66]:
y = pd.concat([y_train, y_test])

Połącz obiekty _X_ oraz _y_ w jeden obiekt _DataFrame_.

In [68]:
pd.concat([X,y],axis=1)

price    weight  size_M  size_XL  color_green  color_red  gender_male  \
2 -0.461266 -1.603567       1        0            0          0            1   
4 -0.922531  0.029696       1        0            0          1            0   
3  0.230633 -0.415740       0        0            1          0            0   
1 -0.691898  0.623610       0        0            1          0            1   
0  1.845062  1.366002       0        1            0          1            0   

   bought  
2       1  
4       1  
3       0  
1       0  
0       1