<a href="https://colab.research.google.com/github/lukaszplust/data-science-learn/blob/main/Numpy_challenge_30_days.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Day 1

In [5]:
import numpy as np


arr = np.zeros(shape = (5,5),dtype="int")
print(arr)

In [6]:
print(arr)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
arr = np.full(shape = (10,10), fill_value= 8, dtype = "float32")
print(arr)

[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [11]:
np.arange(10,100,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [7]:
arr = np.arange(10,100,1)
print(arr.reshape(9,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
arr = np.eye(8, dtype = "int16")
print(arr)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [17]:
arr = np.arange(1,25,1)
arr.reshape((2,3,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [18]:
import numpy as np


arr = np.array(
    [
        ['4', '3', '6', '2', '1'],
        ['7', '2', '1', '2', '6'],
    ],
    dtype='<U1',
)

In [28]:
#[i.astype("float16") for i in arr] NiE SMIGA

In [26]:
arr = arr.astype("float16")
print(arr)

[[4. 3. 6. 2. 1.]
 [7. 2. 1. 2. 6.]]


In [42]:
arr = np.arange(1,6,1)
arr = arr.reshape((0,5))
print(arr)

ValueError: ignored

In [49]:
arr = np.random.randint(1, 10, size=5)

print(arr)

[8 7 1 6 8]


In [44]:
arr = np.array([4, 5, 67, 8, 2])
print(arr)

[ 4  5 67  8  2]


In [ ]:
arr = np.random.rand(5,1)
print(arr)

Day 2

In [2]:
np.diag?

In [12]:
x = np.arange(10)
arr = np.diag(x)
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [10]:
arr = np.diag(x)

In [11]:
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [26]:
arr = np.ones(shape=(4, 4), dtype='int')

In [27]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.pad?

In [36]:
arr = np.ones(shape=(4, 4), dtype='int')
arr = np.pad(arr * 5,pad_width=1,constant_values=(0))#constant values -> wartosc do wypełnienia
print(arr)

[[0 0 0 0 0 0]
 [0 5 5 5 5 0]
 [0 5 5 5 5 0]
 [0 5 5 5 5 0]
 [0 5 5 5 5 0]
 [0 0 0 0 0 0]]


In [83]:
arr = np.zeros(shape=(6, 6), dtype='int')
arr[::2, ::2] = 2
arr[1::2,::2] = 4
arr

array([[2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0],
       [2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0],
       [2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0]])

In [84]:
arr = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

In [87]:
np.full_like?

In [88]:
arr = np.full_like(arr, 9.99)
print(arr)

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


In [89]:
np.tri?

In [99]:
arr = np.ones(shape=(6,6))
arr = np.tri(6,6,0)
arr

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [100]:
arr = np.array(
    [
        [False, True, True, False, True],
        [False, False, True, True, True],
    ]
)

In [104]:
arr = arr.astype(np.int8)
print(arr)

[[0 1 1 0 1]
 [0 0 1 1 1]]


In [123]:
arr = np.random.rand(12)
arr = arr.reshape(2,6)
arr = arr.astype("int32")
print(arr)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
