<a href="https://colab.research.google.com/github/lukaszplust/data-science-learn/blob/main/Regresja_Liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [3]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [6]:
print(Y.shape)
print(Y)

(6, 1)
[[3000]
 [3250]
 [3500]
 [3750]
 [4000]
 [4250]]


In [7]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [8]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [12]:
eta = 0.01 # wskaźnik uczenia, learning rate

#losowa inicjalizacja wag -> macierz 2 na 1
weights = np.random.randn(2, 1)
print(X)
#otrzymamy 2 punkty startowe w0 i w1
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[1.57921282]
 [0.76743473]]


Gradient Prosty

In [14]:
intercept = [] # w0
coef = [] #w1

for i in range(4000):
  gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])
print(weights)

[[2750.]
 [ 250.]]


In [15]:
df = pd.DataFrame(data={'intercept': intercept, 'coef': coef})
df.head()

intercept        coef
0  2749.998868  250.000264
1  2749.998872  250.000263
2  2749.998876  250.000262
3  2749.998880  250.000262
4  2749.998885  250.000261

In [18]:
#w0
px.line(df, y='intercept', width=800, title='Dopasowanie: intercept')

In [17]:
#w1
px.line(df, y='coef', width=800, title='Dopasowanie: coef')